
package visao;

import dao.ConvenioDAO;
import dao.PacienteDAO;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;

import modelo.Convenio;
import modelo.Paciente;
import servicos.ConvenioServicos;
import servicos.ServicosFactory;

public class GuiCadPaciente extends javax.swing.JInternalFrame {

    /**
     * Creates new form GuiCadPaciente
     */
    public GuiCadPaciente() {
        initComponents();
        preencherCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jlNome = new javax.swing.JLabel();
        jlCpf = new javax.swing.JLabel();
        jlEndereco = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jtEndereco = new javax.swing.JTextField();
        jlEspecialidade = new javax.swing.JLabel();
        jlDataNasc = new javax.swing.JLabel();
        jlTelefone = new javax.swing.JLabel();
        jlEmail1 = new javax.swing.JLabel();
        jtEmail1 = new javax.swing.JTextField();
        jlRG = new javax.swing.JLabel();
        jtRG = new javax.swing.JTextField();
        jcConvenio = new javax.swing.JComboBox<>();
        jtCpf = new javax.swing.JFormattedTextField();
        jtDataNasc = new javax.swing.JFormattedTextField();
        jtTelefone = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jbLimpar = new javax.swing.JButton();
        jbCadastrar1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("CADASTRO PACIENTE");

        jLayeredPane1.setBackground(new java.awt.Color(204, 255, 255));
        jLayeredPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLayeredPane1.setOpaque(true);

        jlNome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlNome.setText("Nome * ");
        jLayeredPane1.add(jlNome);
        jlNome.setBounds(60, 80, 70, 30);

        jlCpf.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlCpf.setText("CPF *");
        jLayeredPane1.add(jlCpf);
        jlCpf.setBounds(60, 120, 90, 30);

        jlEndereco.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlEndereco.setText("Endereço *");
        jLayeredPane1.add(jlEndereco);
        jlEndereco.setBounds(50, 200, 100, 30);
        jLayeredPane1.add(jtNome);
        jtNome.setBounds(160, 80, 210, 30);
        jLayeredPane1.add(jtEndereco);
        jtEndereco.setBounds(160, 200, 210, 30);

        jlEspecialidade.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlEspecialidade.setText("Convênio");
        jLayeredPane1.add(jlEspecialidade);
        jlEspecialidade.setBounds(60, 360, 100, 30);

        jlDataNasc.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jlDataNasc.setText("Data Nascimento *");
        jLayeredPane1.add(jlDataNasc);
        jlDataNasc.setBounds(40, 320, 160, 30);

        jlTelefone.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlTelefone.setText("Telefone *");
        jLayeredPane1.add(jlTelefone);
        jlTelefone.setBounds(50, 240, 100, 30);

        jlEmail1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlEmail1.setText("E-mail");
        jLayeredPane1.add(jlEmail1);
        jlEmail1.setBounds(60, 280, 90, 30);
        jLayeredPane1.add(jtEmail1);
        jtEmail1.setBounds(160, 280, 210, 30);

        jlRG.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlRG.setText("RG");
        jLayeredPane1.add(jlRG);
        jlRG.setBounds(60, 160, 90, 30);
        jLayeredPane1.add(jtRG);
        jtRG.setBounds(160, 160, 210, 30);

        jLayeredPane1.add(jcConvenio);
        jcConvenio.setBounds(160, 360, 150, 30);

        try {
            jtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jLayeredPane1.add(jtCpf);
        jtCpf.setBounds(160, 120, 90, 30);

        try {
            jtDataNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("   ##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jLayeredPane1.add(jtDataNasc);
        jtDataNasc.setBounds(220, 320, 70, 30);

        try {
            jtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jLayeredPane1.add(jtTelefone);
        jtTelefone.setBounds(190, 240, 90, 30);

        jLabel1.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("* Campo Obrigatório");
        jLayeredPane1.add(jLabel1);
        jLabel1.setBounds(390, 40, 130, 19);

        jLayeredPane2.setBackground(new java.awt.Color(255, 255, 255));
        jLayeredPane2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLayeredPane2.setOpaque(true);

        jbLimpar.setText("limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });
        jLayeredPane2.add(jbLimpar);
        jbLimpar.setBounds(290, 20, 140, 40);

        jbCadastrar1.setText("cadastrar");
        jbCadastrar1.setMinimumSize(new java.awt.Dimension(78, 20));
        jbCadastrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrar1ActionPerformed(evt);
            }
        });
        jLayeredPane2.add(jbCadastrar1);
        jbCadastrar1.setBounds(80, 20, 140, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
                    .addComponent(jLayeredPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrar() {
        try {

            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

            Paciente pac = new Paciente();

            // Atribuindo valores aos atributos do Paciente com base nos campos preenchidos pelo usuário na tela
            pac.setNome(jtNome.getText());
            pac.setEndereco(jtEndereco.getText());
            pac.setDataNascimento(sdf.parse(jtDataNasc.getText()));
            pac.setTelefone(jtTelefone.getText());
            pac.setCpf(jtCpf.getText());
            pac.setRg(jtRG.getText());

            // Verificando se um convênio foi selecionado no JComboBox
            if (!(jcConvenio.getSelectedIndex() == 0)) {

                // Obtendo o nome do convênio selecionado pelo usuário
                String conv = jcConvenio.getSelectedItem().toString();

                // Criando objeto ConvenioDAO para buscar o convênio no banco de dados
                ConvenioDAO convDAO = new ConvenioDAO();

                // Buscando o convênio no banco de dados com base no nome selecionado pelo usuário
                Convenio convenio = convDAO.buscarConvenioFiltro(conv);

                // Atribuindo o ID do convênio ao paciente
                pac.setConvenio(convenio.getIdConvenio());

            } else {
                JOptionPane.showMessageDialog(this,
                        "Selecione um produto");
            } // fecha else

       //mudanças
       
       
       
           // Criando objeto PacienteDAO para cadastrar o paciente no banco de dados
            PacienteDAO pacDAO = new PacienteDAO();
            pacDAO.cadastrarPaciente(pac);

            // Mensagem de sucesso
            JOptionPane.showMessageDialog(this, "Paciente cadastrado com sucesso!");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "ERRO! " + e.getMessage());
        } // fecha catch

    }// fecha método

    //apaga valores dos campos
    private void limpar() {
        jtNome.setText("");
        jtEndereco.setText("");
        jtCpf.setText("");
        jtDataNasc.setText("");
        jtRG.setText("");
        jtTelefone.setText("");
        jtEmail1.setText("");
    }// fecha método

    
    // metodo para preencher o combo box com os produtos cadastrados no banco de dados
    private void preencherCombo() {
        try {

            // Buscando objeto ProdutoServicos
            ConvenioServicos ps = ServicosFactory.getConvenioServicos();

            /*
             * Criando um ArrayList<ProdutoVO> vazio
             * para receber o ArrayList com os dados
             */
            ArrayList<Convenio> p = new ArrayList<>();

            // Recebendo o ArrayList cheio em produtos
            p = ps.buscarConvenio();

            // Adicionando os dados do ArrayList no JComboBox
            jcConvenio.addItem("-Selecione-");
            for (int i = 0; i < p.size(); i++) {

                // Adicionando o nome do convênio ao JComboBox
                jcConvenio.addItem(p.get(i).getNomeConvenio());

            } // fecha for

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Erro! " + e.getMessage());
        } // fecha catch
    }// fecha classe

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {
        limpar();
    }

    private void jbCadastrar1ActionPerformed(java.awt.event.ActionEvent evt) {
        boolean ok = true;
        
         if(jtNome.getText().isEmpty()){
            JOptionPane.showMessageDialog(GuiCadPaciente.this, "O Campo NOME é obrigatório!","INFORMAÇãO",JOptionPane.INFORMATION_MESSAGE);
                jtNome.requestFocusInWindow();
            ok = false;
        }
         
         if(jtCpf.getText().isEmpty()){
            JOptionPane.showMessageDialog(GuiCadPaciente.this, "O Campo CPF é obrigatório!","INFORMAÇãO",JOptionPane.INFORMATION_MESSAGE);
                jtCpf.requestFocusInWindow();
            ok = false;
        }
         
         if(jtDataNasc.getText().isEmpty()){
            JOptionPane.showMessageDialog(GuiCadPaciente.this, "O Campo DATA DE NASCIMENTO é obrigatório!","INFORMAÇãO",JOptionPane.INFORMATION_MESSAGE);
                jtDataNasc.requestFocusInWindow();
            ok = false;
        }
         
         if(jtEndereco.getText().isEmpty()){
            JOptionPane.showMessageDialog(GuiCadPaciente.this, "O Campo ENDEREÇO é obrigatório!","INFORMAÇãO",JOptionPane.INFORMATION_MESSAGE);
                jtEndereco.requestFocusInWindow();
            ok = false;
        }
         
         if(jtTelefone.getText().isEmpty()){
            JOptionPane.showMessageDialog(GuiCadPaciente.this, "O Campo TELEFONE é obrigatório!","INFORMAÇãO",JOptionPane.INFORMATION_MESSAGE);
                jtTelefone.requestFocusInWindow();
            ok = false;
        }
         if(ok){
        cadastrar();
        limpar();
         }else
         JOptionPane.showMessageDialog(GuiCadPaciente.this, "Cadastro NÃO REALIZADO! \n Verifique as infomações","INFORMAÇãO",JOptionPane.INFORMATION_MESSAGE);    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JButton jbCadastrar1;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JComboBox<String> jcConvenio;
    private javax.swing.JLabel jlCpf;
    private javax.swing.JLabel jlDataNasc;
    private javax.swing.JLabel jlEmail1;
    private javax.swing.JLabel jlEndereco;
    private javax.swing.JLabel jlEspecialidade;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlRG;
    private javax.swing.JLabel jlTelefone;
    private javax.swing.JFormattedTextField jtCpf;
    private javax.swing.JFormattedTextField jtDataNasc;
    private javax.swing.JTextField jtEmail1;
    private javax.swing.JTextField jtEndereco;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtRG;
    private javax.swing.JFormattedTextField jtTelefone;
    // End of variables declaration//GEN-END:variables
}
